###############################################################################
# (c) 2025 W. Spann Systems Consulting
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

"""
This module provides support for generating sealed Polynomial Pedersen commitments over elliptic curves to any
single-variate polynomial over a finite cyclic field (e.g., where the polynomial's coefficients and its independent `x`
and dependent `y` variables are members of `F_p`, where `p` is a prime number), as well as revealed (unsealed)
polynomial commitments.

Polynomial Pedersen commitments are homomorphic, meaning that commitments to polynomials can be combined (e.g., added,
subtracted, or multiplied by a scalar) to produce commitments to new polynomials without revealing the underlying
polynomials

Additionally, the module supports generating and verifying non-interactive zero-knowledge (NIZK) proofs of evaluation
for such secret polynomials (i.e., a prover who has committed to a secret polynomial can produce an NIZK proof that the
polynomial evaluates to a specific `y` value at a given `x` value, without revealing any information about the
polynomial itself).
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import reduce
from typing import cast

import galois

from Cryptodome.PublicKey import ECC

from galois import FieldArray

from scriptless_zkp.ecc.commitments.pedersen import (
    SealedPedersenCommitment, RevealedPedersenCommitment, PedersenCommitmentContext
)
from scriptless_zkp.ecc.weierstrass_curves import WeierstrassEllipticCurveConfig


@dataclass(frozen=True)
class SealedPolynomialPedersenCommitment:
    coefficient_commitments: list[SealedPedersenCommitment]
    field: type[FieldArray]

    @property
    def degree(self) -> int:
        return len(self.coefficient_commitments) - 1

    @property
    def curve_config(self) -> WeierstrassEllipticCurveConfig:
        return self.coefficient_commitments[0].curve_config

    @property
    def nums_generator(self) -> ECC.EccPoint:
        return self.coefficient_commitments[0].nums_generator

    def verify_integrity(self) -> bool:
        """
        Verifies that all coefficient commitments are valid points on the elliptic curve defined in the Pedersen
        commitment context.
        :return: True if all coefficient commitments are valid points on the curve; False otherwise.
        """
        return all(
            self.curve_config.is_point_on_curve(
                self.coefficient_commitments[i].commitment_point
            )
            for i in range(len(self.coefficient_commitments))
        )

    def verify_evaluation_proof(self, proof: PolynomialPedersenEvaluationProof) -> bool:
        return proof.verify(self)


@dataclass(frozen=True)
class RevealedPolynomialPedersenCommitment:
    coefficient_commitments: list[RevealedPedersenCommitment]
    blinding_factors: list[int]
    committed_polynomial: galois.Poly

    @property
    def coefficients(self) -> list[int]:
        return self.committed_polynomial.coeffs.tolist()

    @property
    def degree(self) -> int:
        return self.committed_polynomial.degree

    @property
    def field(self) -> type[FieldArray]:
        return cast(type[FieldArray], self.committed_polynomial.field)

    @property
    def curve_config(self) -> WeierstrassEllipticCurveConfig:
        return self.coefficient_commitments[0].curve_config

    @property
    def nums_generator(self) -> ECC.EccPoint:
        return self.coefficient_commitments[0].nums_generator

    def _evaluate_polynomial(self, x: int) -> int:
        """
        Evaluates the committed polynomial at the given `x` value, returning the result as an integer in `Z_q`, where
        `q` is the Polynomial Pedersen Commitment's elliptic curve sub-group's order (i.e., `|<G>|` where `<G>` is the
        sub-group generated by the public base point `G`).

        :param x: the `x` value at which to evaluate the committed polynomial, which must be in the range `[0, p)` where
                  `p` is the polynomial's coefficient's field characteristic (i.e., `p` for a polynomial over `F_p`).
        :return: the result of evaluating the committed polynomial at the given `x` value, as an integer in `Z_q`,
                 where `q` is the Polynomial Pedersen Commitment's elliptic curve sub-group's order.
        :raises ValueError: if the provided `x` value is out of range for the field (i.e., not in the range `[0, p)`
                where `p` is the field characteristic).
        """
        if not (0 <= x < self.field.characteristic):
            raise ValueError(f"Evaluation point x is out of range for the field F_{self.field.characteristic}.")

        return int(self.committed_polynomial(x)) % self.curve_config.order

    def generate_evaluation_proof(self, x: int) -> PolynomialPedersenEvaluationProof:
        """
        Generates a non-interactive zero-knowledge (NIZK) proof that the committed polynomial evaluates to `y` at the
        given `x` value, without revealing any information about the polynomial itself.

        0. Precondition: The prover has already committed to a secret polynomial using a Polynomial Pedersen commitment,
        resulting in a `SealedPolynomialPedersenCommitment` and a corresponding `RevealedPolynomialPedersenCommitment`
        (which includes the secret blinding factors used to produce the coefficient commitments).
            a. The prover wants to prove to a verifier that the committed polynomial evaluates to `y` at a specific `x`
               value, without revealing the polynomial itself.
            b. The verifier knows the `SealedPolynomialPedersenCommitment` and the `x` value, but does not know the
               polynomial or its coefficients.
        1. The prover and verifier agree on the `x` value at which the polynomial will be evaluated, which must be in
        the range `[0, p)` where `p` is the field characteristic, with the verifier providing the `x` value to the
        prover.
        2. The prover evaluates the committed polynomial at the given `x` value to obtain `y`.
        3. The prover computes a non-interactive zero-knowledge proof (NIZK) that the committed polynomial evaluates to
        `y` at the given `x` value, using the secret blinding factors from its (revealed) coefficient commitments.
            - This proof `𝜋` is computed as:
                `𝜋 := r_0 + r_1*x + r_2*x^2 + ... + r_d*x^d (mod p)`,
            where `r_i` are the blinding factors for each coefficient commitment, `p` is the field characteristic,
            and `d` is the degree of the polynomial.
        4. The prover sends the pair `(y, 𝜋)` of integers in `Z_p` to the verifier.
        5. The verifier checks that the proof is valid by verifying that the following equation holds
        (i.e., the elliptic curve points produced by the left & right sides are equal), using the coefficient
        commitments from the `SealedPolynomialPedersenCommitment`, provided to the verifier by the prover earlier:
            `y*G + 𝜋*B == C_0 + C_1*x + C_2*x^2 + ... + C_d*x^d`,
        where `C_i` are the coefficient commitments, `G` is the Pedersen commitment base point (common generator), and
        `B` is the Pedersen commitment NUMS generator, `p` is the field characteristic, and `d` is the degree of the
        polynomial.

        :param x: the `x` value at which to evaluate the committed polynomial, which must be in the range `[0, p)` where
                  `p` is the field characteristic.
        :return: a `PolynomialPedersenEvaluationProof` proving in zero-knowledge the evaluation of the committed
                 polynomial at the provided `x` value equals `y`, encapsulated as the tuple `(x, y, proof)` of integers
                 in `Z_p`, where `p` is the field characteristic.
        :raises ValueError: if the provided `x` value is out of range for the polynomial's coefficients' field
                (i.e., not in the range `[0, p)` where `p` is the field characteristic).
        """
        # Evaluate the committed polynomial at the given x value, and reduce modulo the curve sub-group's (<G>) order q.
        y: int = self._evaluate_polynomial(x)

        # Compute a zero-knowledge proof that the committed polynomial evaluates to y at x:
        #     `𝜋 := r_0 + r_1*x + r_2*x^2 + ... + r_d*x^d (mod q)`,
        # where `r_i` are the blinding factors for each coefficient commitment, `q` is the curve sub-group's order,
        # and `d` is the degree of the polynomial.
        proof: int = sum(
            blinding_factor * pow(x, i, self.curve_config.order)
            for i, blinding_factor in enumerate(self.blinding_factors)
        ) % self.curve_config.order

        # Return the NIZK polynomial evaluation proof, which encapsulates the tuple `(x, y, 𝜋)` of integers modulo `q`.
        return PolynomialPedersenEvaluationProof(x, y, proof)


@dataclass(frozen=True)
class PolynomialPedersenEvaluationProof:
    x: int
    y: int
    proof: int

    @property
    def evaluation(self) -> int:
        return self.y

    def verify(
            self,
            sealed_commitment: SealedPolynomialPedersenCommitment
    ) -> bool:
        """
        Verifies a non-interactive zero-knowledge (NIZK) proof that the committed polynomial evaluates to `y` at the
        given `x` value, without revealing any information about the polynomial itself.

        This verification checks that the following equation holds (i.e., the elliptic curve points produced by the
        left & right sides are equal), using the coefficient commitments `[C_i]_d` from this
        `SealedPolynomialPedersenCommitment`:

            `y*G + 𝜋*B == C_0 + C_1*x + C_2*x^2 + ... + C_d*x^d`,

        where `C_i` are the coefficient commitments, `G` is the Pedersen commitment base point (common generator),
        `B` is the Pedersen commitment NUMS generator, `p` is the field characteristic, and `d` is the degree of the
        polynomial.

        :param sealed_commitment: the `SealedPolynomialPedersenCommitment` containing the coefficient commitments
                                  corresponding to the committed polynomial, for which this zero-knowledge evaluation
                                  proof is being verified.
        :return: True if the proof is valid (i.e., the proof verification equation holds); False otherwise.
        :raises ValueError: if the provided `x` value is out of range for the polynomial's coefficient field `F_p`
                            (i.e., not in the range `[0, p)` where `p` is the field characteristic); or if the provided
                            evaluation value `y` is not in the range `[0, q)`, where q is the elliptic curve sub-group's
                            order.
        """
        if not (0 <= self.x < sealed_commitment.field.characteristic):
            raise ValueError(
                f"Evaluation point 'x' is out of range for the field 'F_{sealed_commitment.field.characteristic}'."
            )
        if not (0 <= self.y < sealed_commitment.curve_config.order):
            raise ValueError(
                f"Evaluation result 'y' is out of range for the ECC Polynomial Pedersen Commitment's elliptic curve"
                f" sub-group's order q."
            )

        G: ECC.EccPoint = sealed_commitment.curve_config.base_point
        B: ECC.EccPoint = sealed_commitment.nums_generator

        # Left side: y*G + 𝜋*B
        left_side: ECC.EccPoint = G * self.y + B * self.proof

        # Right side: C_0 + C_1*x + C_2*x^2 + ... + C_d*x^d
        right_side: ECC.EccPoint = reduce(
            lambda accum, pt:
            accum + pt,  # elliptic curve point addition
            [sealed_commitment.coefficient_commitments[i].commitment_point
                * pow(self.x, i, sealed_commitment.curve_config.order)
             for i in range(len(sealed_commitment.coefficient_commitments))],
            sealed_commitment.curve_config.identity  # start point additions w/ curve's identity element: O (i.e., point-at-infinity)
        )

        return left_side == right_side


class PolynomialPedersenContext:
    def __init__(self, field: type[FieldArray], pedersen_context: PedersenCommitmentContext):
        if not galois.is_prime(field.characteristic):
            raise ValueError("Field must be a field with prime characteristic (e.g., F_p or F_p^m, where p is prime).")

        self.field = field
        self.pedersen_context = pedersen_context

    @property
    def curve_config(self) -> WeierstrassEllipticCurveConfig:
        return self.pedersen_context.curve_config

    def commit_to_polynomial(
            self,
            polynomial: galois.Poly
    ) -> tuple[SealedPolynomialPedersenCommitment, RevealedPolynomialPedersenCommitment]:
        if polynomial.field is not self.field:
            raise ValueError("Polynomial must be defined over the same field as the Polynomial Pedersen context.")
        elif polynomial.degree >= self.field.characteristic:
            raise ValueError(
                f"Polynomial degree must be less than the field characteristic 'p': {self.field.characteristic}"
            )
        elif polynomial.degree < 1:
            raise ValueError("Polynomial degree must be at least 1 (i.e., constant polynomials are not supported).")

        coefficient_commitments: list[SealedPedersenCommitment] = []
        revealed_coefficient_commitments: list[RevealedPedersenCommitment] = []

        # Enumerate the polynomial coefficients in ascending order (i.e., from the constant term to the highest-degree
        # term), committing to each coefficient individually using the underlying Pedersen commitment context.
        for i, coeff in enumerate(reversed(polynomial.coeffs)):
            coeff_int: int = int(coeff)
            if not (0 <= coeff_int < self.field.characteristic):
                raise ValueError(
                    f"Polynomial coefficient a_{i} is out of range for the field F_{self.field.characteristic}."
                )

            sealed_commitment, revealed_commitment = self.pedersen_context.commit(coeff_int)

            coefficient_commitments.append(sealed_commitment)
            revealed_coefficient_commitments.append(revealed_commitment)

        return SealedPolynomialPedersenCommitment(
            coefficient_commitments=coefficient_commitments,
            field=self.field
        ), RevealedPolynomialPedersenCommitment(
            coefficient_commitments=revealed_coefficient_commitments,
            blinding_factors=[rc.blinding_factor for rc in revealed_coefficient_commitments],
            committed_polynomial=polynomial
        )
